### ISSUE TITLE
Header dropdowns styling bug with react-bootstrap ^1.0.0

### ISSUE THREAD

**Issue by wggley** [codedthemes/datta-able-free-react-admin-template#1]
Theme version for react-bootstrap is ^1.0.0-beta.5.

But after 1.0.0 version upgrade layout is broken for Header DropdownMenu:

![image](https://user-images.githubusercontent.com/13734836/101827829-8a8d5b00-3b0f-11eb-8c44-fa26a8ded81f.png)
![image](https://user-images.githubusercontent.com/13734836/101827932-ab55b080-3b0f-11eb-8d79-fe2b8120fba1.png)

The issue maybe is related to Popover library being updated, I really dunno.

A quick fix:

src\assets\scss\partials\menu\_menu-lite.scss

```css
    .mr-auto {
        .dropdown-menu {
            margin-left: -20px !important;
        }
    }

    .ml-auto {
        float: right;

        .dropdown-menu {
            margin-left: 20px !important;
        }
    }
```
