### ISSUE TITLE
Mobile (or small screens) is not possible to scroll down Left Menu

### ISSUE THREAD

**Issue by wggley** [codedthemes/datta-able-free-react-admin-template#2]
![image](https://user-images.githubusercontent.com/13734836/101828187-f8d21d80-3b0f-11eb-836e-8f50a4c2dc79.png)

**Comment by wggley** [comment]
This also happens for fullscreen mode.

Quick fix:

```css
.fullscreen-enabled .pcoded-navbar {
    position: absolute;
}
```
