### ISSUE TITLE
Can't scroll pages on Fullscreen

### ISSUE THREAD

**Issue by wggley** [codedthemes/datta-able-free-react-admin-template#3]
No scrollbar is showing:

![image](https://user-images.githubusercontent.com/13734836/101832094-a5fb6480-3b15-11eb-95bd-ac72de09b9ba.png)

quick fix:
src\assets\scss\partials\menu_menu-lite.scss
```css
.fullscreen-enabled {
    overflow-y: auto;
}
```
